=== gregtyler/scoreboard/data/schema.json
{
  "$id": "https://gregtyler.co.uk/scoring.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "title",
    "game",
    "players",
    "rounds"
  ],
  "properties": {
    "_id": {
      "type": "string",
      "format": "uuid"
    },
    "title": {
      "type": "string"
    },
    "labels": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "game": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "_id"
          ],
          "properties": {
            "_id": {
              "type": "string",
              "format": "uuid"
            }
          }
        },
        {
          "$ref": "#/definitions/game"
        }
      ]
    },
    "location": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "_id"
          ],
          "properties": {
            "_id": {
              "type": "string",
              "format": "uuid"
            }
          }
        },
        {
          "$ref": "#/definitions/location"
        }
      ]
    },
    "players": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "oneOf": [
              {
                "type": "object",
                "required": [
                  "_id"
                ],
                "properties": {
                  "_id": {
                    "type": "string",
                    "format": "uuid"
                  }
                }
              },
              {
                "$ref": "#/definitions/player"
              }
            ]
          },
          {
           	"type": "object",
            "required": ["colour"],
            "properties": {
              "colour": {
                "type": "string"
              }
            }
          }
        ]
      }
    },
    "rounds": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/round"
      }
    }
  },
  "definitions": {
    "location": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "game": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "player": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "round": {
      "type": "object",
      "required": [
        "scores"
      ],
      "properties": {
        "label": {
          "type": "string"
        },
        "scores": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/playerScore"
          }
        }
      }
    },
    "playerScore": {
      "type": "object",
      "required": [
        "player",
        "score"
      ],
      "properties": {
        "player": {
          "type": "number"
        },
        "score": {
          "type": "number"
        }
      }
    }
  }
}

=== gregtyler/scoreboard/data/example.json
{
  "_id": "3cc7249f-6d05-485a-9892-6e8d8f42bf4e",
  "title": "Parks - 13th June 2022 in Wildcat",
  "labels": ["competitive", "interrupted"],
  "game": {
    "name": "Parks"
  },
  "location": {
    "_id": "7f088186-075c-46c0-a4c2-448e9395abd7"
  },
  "players": [
    {
      "name": "Greg",
      "colour": "blue"
    },
    {
      "_id": "6f088186-075c-46c0-a4c2-448e9395abd7",
      "colour": "red"
    }
  ],
  "rounds": [
    {
      "label": "Final score",
      "scores": [
        { "player": 0, "score": 45 },
        { "player": 1, "score": 47 }
      ]
    }
  ]
}
